name: Update expo
on: [push]

jobs:
  easUpdate:
    name: EAS Update
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'github actions - gen update')

    steps:
      
      - name: Checkout repository
        id: get_repo
        uses: actions/checkout@v3
      
            
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
            
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPOTOKEN }}
      
            
      - name: Install dependencies
        run: yarn install
      
            
      - name: Configure EAS project
        run: eas init --id ${{ secrets.EXPOPROJECTID }} --non-interactive
      
            
      - name: Create preview
        id: preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto
      
      - name: Set Qr Code
        run: |
          curl --location --request GET 'https://us-central1-flaxboll.cloudfunctions.net/fireUserUpdateQr' \
          --header 'Content-Type: text/plain' \
          --data '{"qrcodeUrl":"${{ steps.preview.outputs.qr }}","userID":"${{ secrets.USERID }}","projectID":"${{ secrets.PROJECTID }}"}'
